/* eslint-disable */
/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import { a } from "@aws-amplify/data-schema";
import { configure } from "@aws-amplify/data-schema/internals";
import { secret } from "@aws-amplify/backend";

export const schema = configure({
    database: {
        identifier: "IDxF2MUZdRPpywlzYkCeZcw",
        engine: "postgresql",
        connectionUri: secret("SQL_CONNECTION_STRING")
    }
}).schema({
    "customers": a.model({
        id: a.id().required(),
        name: a.string().required(),
        email: a.string().required(),
        image_url: a.string().required()
    }).identifier([
        "id"
    ]),
    "invoices": a.model({
        id: a.id().required(),
        customer_id: a.id().required(),
        amount: a.integer().required(),
        status: a.string().required(),
        date: a.date().required()
    }).identifier([
        "id"
    ]),
    "users": a.model({
        id: a.id().required(),
        name: a.string().required(),
        email: a.string().required(),
        password: a.string().required()
    }).identifier([
        "id"
    ])
});
